genres = ["Role-Playing Game", "Action/Adventure", "Fighting", "Puzzle", "Sports/Racing", "First-Person Shooter", "Horror/Survival Horror"]

platforms = ["PS5", "Xbox Series X/S", "Switch", "PC"]

#data info is formatted as follows: [name/title of game, genre, opencritic score, platform(s)]
game_data = [["The Elders Scrolls V: Skyrim - Special Edition", "Role-Playing Game", "83", "PS5, Xbox Series X/S, Switch, PC"], 
             ["Baldur's Gate 3", "Role-Playing Game", "96", "PS5, PC"], 
             ["Elden Ring", "Role-Playing Game", "95", "PS5, Xbox Series X/S, PC"],
             ["Cyberpunk 2077", "Role-Playing Game", "83", "PS5, Xbox Series X/S, PC"],
             ["Disco Elysium", "Role-Playing Game", "91", "PS5, Xbox Series X/S, Switch, PC"],
             ["Diablo III", "Role-Playing Game", "88", "PS5, Xbox Series X/S, Switch, PC", ],
             ["Marvel's Guardians of the Galaxy", "Action/Adventure", "82", "PS5, Xbox Series X/S, Switch, PC"],
             ["God of War", "Action/Adventure", "94", "PS5, PC"],
             ["Red Dead Redemption 2", "Action/Adventure", "96", "PS5, Xbox Series X/S, PC"],
             ["A Way Out", "Action/Adventue", "79", "PS5, Xbox Series X/S, PC"],
             ["Marvel's Spider-Man 2", "Action/Adventure", "90", "PS5"],
             ["Star Wars Jedi: Fallen Order", "Action/Adventure", "82", "PS5, Xbox Series X/S, PC"],
             ["Guilty Gear -Strive-", "Fighting", "86", "PS5"],
             ["Street Fighter 6", "Fighting", "92", "PS5, Xbox Series X/S, PC"],
             ["Dragon Ball FighterZ", "Fighting", "86", "PS5, Xbox Series X/S, PC"],
             ["Ultimate Marvel vs. Capcom 3 (HD Edition)", "Fighting", "78", "PS5, Xbox Series X/S, PC"],
             ["Killer Instinct", "Fighting", "77", "Xbox Series X/S, PC"],
             ["Mortal Kombat 1", "Fighting", "84", "PS5, Xbox Series X/S, Switch, PC"],
             ["Return of the Obra Dinn", "Puzzle", "89", "PS5, Xbox Series X/S, Switch, PC"],
             ["The Witness", "Puzzle", "86", "PS5, Xbox Series X/S, PC"],
             ["The Talos Principle", "Puzzle", "87", "PS5, PC"],
             ["Portal 2", "Puzzle", "93", "Switch, PC"],
             ["Baba Is You", "Puzzle", "84", "Switch, PC"],
             ["Return to Monkey Island", "Puzzle", "87", "Switch, PC"],
             ["EA Sports FC 24", "Sports/Racing", "74", "PS5, Xbox Series X/S, Switch, PC"],
             ["Madden NFL 24", "Sports/Racing", "66", "PS5, Xbox Series X/S, PC"],
             ["NBA 2K24", "Sports/Racing", "68", "PS5, Xbox Series X/S, PC"],
             ["Tony Hawk's Pro Skater 1 + 2", "Sports/Racing" "89", "PS5, Xbox Series X/S, PC"],
             ["Rocket League", "Sports/Racing", "87", "PS5, Xbox Series X/S, Switch, PC"],
             ["Forza Motorsport", "Sports/Racing", "84", "Xbox Series X/S, PC"],
             ["Call of Duty: Modern Warfare III", "First-Person Shooter", "58", "PS5, Xbox Series X/S, PC"],
             ["Counter-Strike 2", "First-Person Shooter", "80", "PC"],
             ["Tom Clancy's Rainbow Six Siege", "First-Person Shooter", "76", "PS5, Xbox Series X/S, PC"],
             ["DOOM Eternal", "First-Person Shooter", "89", "PS5, Xbox Series X/S, Switch, PC"],
             ["Titanfall 2", "First-Person Shooter", "87", "PS5, Xbox Series X/S, PC"],
             ["Apex Legends", "First-Person Shooter", "81", "PS5, Xbox Series X/S, PC"],
             ["The Outlast Trials", "Horror/Survival Horror", "72", "PC"],
             ["Alan Wake 2", "Horror/Survival Horror", "89", "PS5, Xbox Series X/S, PC"],
             ["Lethal Company", "Horror/Survival Horror", "N/A", "PC"],
             ["Amnesia: The Bunker", "Horror/Survival Horror", "77", "PS5, Xbox Series X/S, PC"],
             ["Resident Evil 4 (2023)", "Horror/Survival Horror", "92", "PS5, Xbox Series X/S, PC"],
             ["Sons of the Forest", "Horror/Survival Horror", "78", "PC"]]
